spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 36000
        path: /
        name: SESSIONID
      timeout: 36000
logging:
  config: src/main/resources/logback-spring.xml