server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 36000
        path: /
        name: SESSIONID
      timeout: 36000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.conwise.model
  configuration:
    map-underscore-to-camel-case: true
spring:
  application:
    name: connectWise
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      base-url: ${OPEN_BASE_URL}
      chat:
        options:
          model: ${CHAT_MODAL}
#        api-key: ${OPEN_API_KEY}
minio:
  endpoint: ${MINIO_ENDPOINT_ENV}:${MINIO_PORT}/
  credentials:
    username: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
  bucketName: ${MINIO_BUCKET}
  secure: ${MINIO_SECURE}
resource:
  static:
    images: /app/resources/static/images/default-thumbnail.webp
