spring:
  application:
    name: connectWise
  session:
    redis:
      flush-mode: on_save
      namespace: spring:session
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      base-url: ${OPEN_BASE_URL}
      chat:
        options:
          model: ${CHAT_MODAL}
#        api-key: ${OPEN_API_KEY}
minio:
  endpoint: ${MINIO_ENDPOINT_ENV}:${MINIO_PORT}/
  credentials:
    username: ${MINIO_ROOT_USER}
    password: ${MINIO_ROOT_PASSWORD}
  bucketName: ${MINIO_BUCKET}
  secure: ${MINIO_SECURE}
websocket:
  max-connections: 1000
  room:
    max-connections: 5