name: Build and Push Backend Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建并推送Docker镜像
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_USERNAME }}/connectwise-backend:latest
          build-args: |
            POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            DEEPSEEK_API_KEY=${{ secrets.DEEPSEEK_API_KEY }}
            MINIO_USERNAME=${{ secrets.MINIO_USERNAME }}
            MINIO_PASSWORD=${{ secrets.MINIO_PASSWORD }}
          cache-from: type=gha
          cache-to: type=gha,mode=max